### Create Animal
POST http://localhost:5000/animals
Content-Type: application/json

{
  "signature": "ABC123",
  "transponderCode": "XYZ789",
  "name": "Burek",
  "color": "Brown",
  "species": 1,
  "sex": 1,
  "birthDate": "2020-01-01T00:00:00Z"
}
