@HostAddress = https://localhost:5000

### Create Animal
POST {{HostAddress}}/animals
Authorization: Bearer {{$auth.token("auth0")}}
Content-Type: application/json

{
  "signature": "ABC123",
  "transponderCode": "XYZ789",
  "name": "Burek",
  "color": "Brown",
  "species": 1,
  "sex": 1,
  "birthDate": "2020-01-01T00:00:00Z"
}

### Get Animal
GET {{HostAddress}}/animals
Authorization: Bearer {{$auth.token("auth0")}}
Content-Type: application/json